### ISSUE TITLE
请问一下这两个缺少文件？

### ISSUE THREAD

**Issue by liupengstyle** [w5688414/BERT-Punctuation-Prediction#1]
from data.prepro_peopledaily import process_data
from utils import batchnize_dataset

**Comment by w5688414** [comment]
@liupengstyle   已经更新

> from data.prepro_peopledaily import process_data
> from utils import batchnize_dataset

**Comment by liupengstyle** [comment]
你好，请教一下基于人民日报数据跑出来的模型，怎么改动去预测自己自己的数据，为啥我预测的时候还是用测试的数据没有用上自己的数据？

**Comment by liupengstyle** [comment]
Traceback (most recent call last):
  File "cn_punctor.py", line 1227, in <module>
    main()
  File "cn_punctor.py", line 1141, in main
    out_str, f1, err, ser = compute_score(target_path,predict_path)
  File "cn_punctor.py", line 1212, in compute_score
    err = round((100.0 - float(total_correct) / float(counter - 1) * 100.0), 2)
ZeroDivisionError: float division by zero
INFO:tensorflow:prediction_loop marked as finished
你好，利用训练好的模型去预测自己的数据，待预测的数据要改成什么样子，直接输入没有标点符号的句子报上面的错误，问一下这个怎么解决？

**Comment by w5688414** [comment]
我已经写了一个predict文件了，直接输入没有标点符号的句子，请参考 https://github.com/w5688414/BERT-Punctuation-Prediction/blob/master/bert/run_predict.sh @liupengstyle
